### PR TITLE
Upgrade jhove to 1.20.1

### PR DESCRIPTION
**Pull request by calavano**

### CODE REVIEW

**Comment by jcoyne** [comment]
@calavano Is there something specific you need in this version or some bug this fixes?

**Comment by calavano** [comment]
@jcoyne This addresses the problems we're having with JHove failing with PDFs in the technical-metadata in assemblyWF. A couple objects with the error state at the moment are xq775hq1450 and cv431jj2987.

**Comment by jcoyne** [comment]
@calavano thank you.  Please leave a justification in the commit message in the future that  what you did *and* why you did it.  This makes it so much easier to understand the repository when you're looking into the past.

**Comment by mjgiarlo** [comment]
@calavano @sul-dlss/infrastructure-team I can confirm that JHOVE version 1.16.x and greater get past the voluminous `buildSubtree` errors that JHOVE 1.14 throws with certain PDFs. Should we cut a new release of `jhove-service` and work it into common-accessioning, or is there a reason to be more cautious about bumping this? At least, it would be good to test in stage?

cc: @andrewjbtw

**Comment by jcoyne** [comment]
@mjgiarlo yes, please cut a new release.  Since JHOVE has this as a minor release, I think we could  make our release  a minor release too.

**Pull request merged**
